"""sync schema with models

Revision ID: 2a295c93d2de
Revises: b7c8ad3ec78d
Create Date: 2026-06-24 00:26:27.733932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a295c93d2de'
down_revision: Union[str, None] = 'b7c8ad3ec78d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heal_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('original_selector', sa.String(length=512), nullable=False),
    sa.Column('healed_selector', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('llm_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heal_events_run_id'), 'heal_events', ['run_id'], unique=False)
    op.create_index('ix_heal_events_run_id_step_index', 'heal_events', ['run_id', 'step_index'], unique=False)
    op.create_table('step_diagnosis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_diagnosis_run_id'), 'step_diagnosis', ['run_id'], unique=False)
    op.create_index('ix_step_diagnosis_run_id_step_index', 'step_diagnosis', ['run_id', 'step_index'], unique=True)
    op.create_index(op.f('ix_llm_configs_is_default'), 'llm_configs', ['is_default'], unique=False)
    op.create_index(op.f('ix_run_steps_run_id'), 'run_steps', ['run_id'], unique=False)
    op.create_index('ix_run_steps_run_id_step_index', 'run_steps', ['run_id', 'step_index'], unique=False)
    op.add_column('runs', sa.Column('narrative', sa.String(), nullable=True))
    op.add_column('runs', sa.Column('narrative_generated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_test_case_id'), 'runs', ['test_case_id'], unique=False)
    op.add_column('test_cases', sa.Column('cookies_json', sa.JSON(), nullable=True))
    # server_default backfills existing rows; matches the model's Python-side default ("on")
    op.add_column('test_cases', sa.Column('self_heal', sa.String(length=16), nullable=False, server_default='on'))
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_column('test_cases', 'self_heal')
    op.drop_column('test_cases', 'cookies_json')
    op.drop_index(op.f('ix_runs_test_case_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_column('runs', 'narrative_generated_at')
    op.drop_column('runs', 'narrative')
    op.drop_index('ix_run_steps_run_id_step_index', table_name='run_steps')
    op.drop_index(op.f('ix_run_steps_run_id'), table_name='run_steps')
    op.drop_index(op.f('ix_llm_configs_is_default'), table_name='llm_configs')
    op.drop_index('ix_step_diagnosis_run_id_step_index', table_name='step_diagnosis')
    op.drop_index(op.f('ix_step_diagnosis_run_id'), table_name='step_diagnosis')
    op.drop_table('step_diagnosis')
    op.drop_index('ix_heal_events_run_id_step_index', table_name='heal_events')
    op.drop_index(op.f('ix_heal_events_run_id'), table_name='heal_events')
    op.drop_table('heal_events')
    # ### end Alembic commands ###
